# site properties and page defaults
title: 고성능구조시스템연구실
subtitle: Sustainable and Advanced Structural System Laboratory
logo-text: false
url: "https://labhomepage.github.io"
baseurl: "/sassl"
description: Sustainable and Advanced Structural System Laboratory.
header: images/Labhompage logo.png
footer: images/Labhompage logo simple.png
proofer: false

# site social media and other links
links:
  email: dhson@ut.ac.kr
  orcid: 0000-0002-3501-8265
  google-scholar: 0Q-GOQMAAAAJ
  address: "https://www.google.co.kr/maps/place/%ED%95%9C%EA%B5%AD%EA%B5%90%ED%86%B5%EB%8C%80%ED%95%99%EA%B5%90+%EA%B1%B4%EC%B6%95%EA%B4%80+(E12)/data=!3m1!4b1!4m6!3m5!1s0x3564858ad7c001c7:0xc5d1d45d2a769dda!8m2!3d36.9713231!4d127.871814!16s%2Fg%2F11sskrc8cl?entry=ttu&g_ep=EgoyMDI2MDIxOC4wIKXMDSoASAFQAw%3D%3D"
  github: "labhomepage/sassl"

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
