- id: doi:10.1016/j.istruc.2026.111242
  corresponding: "Baek-Il Bae"
  image: /images/Structures_SFRC Size effect.jpg
  
- id: doi:10.1002/suco.70517
  corresponding: "Dong-Hee Son"
  authors:
  - "Chang-Gi Yoo"
  - "Moon-Seok Lee"
  - Seonghwi Song
  - "Baek-Il Bae"
  - "Chang-Sik Choi"
  - "Dong-Hee Son"
  
- id: doi:10.1186/s40069-026-00894-5
  corresponding: "Baek-Il Bae"


- id: doi:10.1186/s40069-024-00760-2
  corresponding: "Dong-Hee Son"


- id: doi:10.1016/j.cemconcomp.2024.105918
  corresponding: "Sungchul Bae"
 
- id: doi:10.1016/j.istruc.2024.107324
  corresponding: "Chang-Sik Choi"
  
- id: doi:10.1016/j.istruc.2024.106733
  corresponding: "Baek-Il Bae"

- id: doi:10.1016/j.istruc.2024.106027
  corresponding:  "Chang-Sik Choi"

- id: doi:10.1016/j.istruc.2024.105940
  corresponding: "Baek-Il Bae"


- id: doi:10.1016/j.conbuildmat.2023.132856
  corresponding: "Sungchul Bae"

- id: doi:10.1016/j.jobe.2023.107188
  corresponding: "Chang-Sik Choi"

- id: doi:10.1016/j.cscm.2023.e02206
  corresponding: "Dong-Hee Son"
  image: /images/CSCM_Nano_bond.jpg

- id: doi:10.1016/j.cscm.2022.e01603
  corresponding:  "Chang-Sik Choi"
  image: /images/CSCM_Nano_mortar and concrete.jpg

- id: doi:10.14359/51734525
  authors: 
    - Dong-Hee Son
    - Baek-Il Bae
    - Chang-Sik Choi
  corresponding: "Chang-Sik Choi"
  image: /images/ACI_DCB.jpg
 
- id: doi:10.1016/j.jobe.2022.104468
  corresponding: "Dong-Hee Son"
  image: /images/JBE_wall Flexural retrofit.jpg

- id: doi:10.3390/ma14144052
  corresponding: "Chang-Sik Choi"
  image: /images/MDPI_Deck_Fire.jpg

- id: doi:10.3390/app11041662
  corresponding: "Chang-Sik Choi"
  image: /images/MDPI_Deck_Flexural.jpg
  
- id: doi:10.3390/su13010182
  corresponding: "Chang-Sik Choi"
  image: /images/MDPI_CCB.jpg

  file: sources.yaml
